### ISSUE TITLE
Hardcoded usage of /run/... for the SHM filesystem tree

### ISSUE THREAD

**Issue by jimklimov** [42ity/fty-shm#4]
Per discussion of #3 the `/run/fty-shm-1/...` pathnames are preferred and were tested to be some 3% faster on the ARM target platform than `/var/run/fty-shm-1/...`  or `/run/fty-shm-1xxxxxxxxxxxxxxxxxx/...` alternatives - apparently, string size matters.

Still, for potential portability's sake, such things should not be hardcoded, and should be made into a `configure` option someday (via an `acinclude.m4` file as supported by zproject).

**Comment by FrancoisRegisDegott-eaton** [comment]
deprecated
